import Hero from '@/components/Hero'
import PopularSection from '@/components/PopularSection'
import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedesk - A poke Info App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.png" />
      </Head>
      <main>
          <Hero/>
          <PopularSection/>
      </main>
    </>
  )
}
